name: ubuntu-charm
version: '0.1'
summary: demo of a snapped charm
description: see summary :-P
base: core18
grade: stable
confinement: classic

parts:
  ubuntu-charm:
    plugin: rust
    source: .
    stage-packages:
     - lsb-release
apps:
  run-hook:
    adapter: none
    command: ./bin/ubuntu-rust